apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  namespace: aap
  labels:
    team: aap
  annotations:
    cnrm.cloud.google.com/delete-contents-on-destroy: "false"
    cnrm.cloud.google.com/project-id: "aap-dev-e48b"
  name: dataset-test
spec:
  description: "Dataset test"
  friendlyName: dataset-test
  location: europe-north1
  projectRef:
    external: aap-dev-e48b
  resourceID: dataset_test

---

apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "aap-dev-e48b"
  name: table-test
  namespace: aap
  labels:
    team: aap
spec:
  description: "Table test"
  resourceID: table_test
  datasetRef:
    name: dataset-test
  friendlyName: table-test
  schema: |
    [
      {
        "name": "deploySha",
        "type": "STRING"
      },
      {
        "name": "repo",
        "type": "STRING"
      }
    ]
