apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  namespace: aap
  labels:
    team: aap
  annotations:
    cnrm.cloud.google.com/delete-contents-on-destroy: "false"
    cnrm.cloud.google.com/project-id: "aap-dev-e48b"
  name: dataset-test
spec:
  description: "Dataset test"
  friendlyName: dataset-test
  location: europe-north1
  projectRef:
    external: aap-dev-e48b
  resourceID: dataset_test
